# Generated by Django 4.0.5 on 2022-06-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
