# Generated by Django 4.0.4 on 2022-06-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactformdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
