# Generated by Django 4.0.5 on 2022-06-08 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactformdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformdata',
            name='contact_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
