# Generated by Django 4.0.5 on 2022-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactformdata_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdata',
            name='contact_time',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
