# Generated by Django 4.0.5 on 2022-06-08 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contactformdata_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformdata',
            name='contact_time',
        ),
        migrations.AddField(
            model_name='contactformdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactformdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
