# Generated by Django 4.0.5 on 2022-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesoffered',
            name='description',
            field=models.TextField(),
        ),
    ]
