# Generated by Django 4.0.4 on 2022-06-10 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_admin', '0002_customernotes_customercontacts_add_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='id',
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_number',
            field=models.IntegerField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
