# Generated by Django 4.0.4 on 2022-06-12 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_admin', '0003_remove_customers_id_customers_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontacts',
            name='customer_number',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='customer_admin.customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customernotes',
            name='customer_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_admin.customers'),
            preserve_default=False,
        ),
    ]
